export const UNIVERSITIES = [
  "Centro Universitário Uninorte- Rio Branco/AC - UNINORTE",
  "ITPAC Cruzeiro do Sul",
  "Universidade Federal do Acre - UFAC",
  "Centro Universitário Cesmac - Maceió - CESMAC",
  "CENTRO UNIVERSITÁRIO DE MACEIÓ - UNIMA",
  "Universidade Estadual de Ciências da Saúde de Alagoas - Maceió - UNCISAL",
  "Universidade Federal de Alagoas - Arapiraca/AL- UFAL",
  "Universidade Federal de Alagoas - UFAL",
  "Afya Faculdade de Ciências Médicas de Itacoatiara",
  "Afya Faculdade de Ciências Médicas de Manacapuru",
  "Centro Universitário CEUNI-FAMETRO - FAMETRO - Manaus-AM",
  "Universidade do Estado do Amazonas -Manaus - UEA",
  "Universidade Federal do Amazonas - campus Coari -AM",
  "Universidade Federal do Amazonas -UFAM",
  "Universidade Nilton Lins - Manaus - UNINILTONLINS",
  "Faculdade Integrado de Macapá/AP",
  "Universidade Federal do Amapá - UNIFAP",
  "AFYA FACULDADE DE CIÊNCIAS MÉDICAS DE ITABUNA",
  "Centro Universitário AGES",
  "Centro Universitário Dom Pedro II",
  "Centro Universitário UniFG- Guanambi - BA",
  "Escola Bahiana de Medicina e Saúde Pública - Salvador- EBMSP",
  "Faculdade AGES de Medicina -- JACOBINA/BA - FAM",
  "Faculdade AGES de Medicina de Irecê",
  "Faculdade de Medicina Pitágoras de Eunápolis",
  "Faculdade de Saúde Santo Agostinho de Vitoria da Conquista - BA - FASA",
  "Faculdade de Tecnologia e Ciências-Salvador/BA - FTC",
  "Faculdade Estácio de Alagoinhas",
  "Faculdade Estácio de Juazeiro",
  "Faculdades Integradas Padrão - FIP Guanambi",
  "Fundação Universidade Federal do Vale do São Francisco - Paulo Afonso/BA",
  "Unime Lauro de Freitas",
  "Universidade do Estado da Bahia - Cabula/Salvador - UNEB",
  "Universidade Estadual de Feira de Santana- BA - UEFS",
  "Universidade Estadual de Santa Cruz- Ilheus/BA - UESC",
  "Universidade Estadual do Sudoeste da Bahia- Jequié - UESB",
  "Universidade Estadual do Sudoeste da Bahia-Vitória da Conquista - UESB",
  "Universidade Federal da Bahia - campus Anísio Teixeira - CAT",
  "Universidade Federal da Bahia - UFBA",
  "Universidade Federal do Oeste da Bahia -Barreiras/BA - UFOB/Barreiras",
  "Universidade Federal do Recôncavo da Bahia - Santo Antônio de Jesus -(BA) - UFRB",
  "Universidade Federal do Sul da Bahia - Teixeira de Freitas/BA - UFSBA",
  "Universidade Salvador/BA - UNIFACS",
  "Centro Universitário INTA-UNINTA - Sobral/CE",
  "Centro Universitário Unichristus - Fortaleza - UNICHRISTUS",
  "Faculdade de Medicina Estácio de Juazeiro do Norte/CE ESTÁCIO FMJ",
  "Universidade de Fortaleza - CE - UNIFOR",
  "Universidade Estadual do Ceará - UECE",
  "Universidade Federal do Cariri - Campus de Barbalha - UFCA/Barbalha",
  "Universidade Federal do Ceará - UFC",
  "Universidade Federal do Ceará- Campus de Sobral - UFC/Sobral",
  "Universidade Regional do Cariri - URCA",
  "Centro Universitário de Brasília - UNICEUB",
  "Centro Universitário do Planalto Central Apparecido dos Santos – UNICEPLAC",
  "Centro Universitário-Instituto Euro Americano de Educação Ciência Tecnologia SCES",
  "Escola Superior de Ciências da Saúde - Brasília - ESCS",
  "Universidade Católica de Brasília",
  "Universidade de Brasília - DF - UNB",
  "Faculdade Multivix Cachoeiro de Itapemirim",
  "Centro Universitário do Espirito Santo- Colatina - UNESC",
  "Escola Superior de Ciências da Santa Casa de Misericórdia de Vitória - EMESCAM",
  "Faculdade Brasileira - Vitória/ES - MULTIVIX VITORIA",
  "Universidade Federal do Espírito Santo- UFES",
  "Universidade Vila Velha - ES -UVV",
  "Centro de Ensino Superior Morgana Potrich Eireli - FAMP (SUB JUDICE)",
  "Centro Universitário de Anápolis - GO - UniEVANGÉLICA",
  "Centro Universitário de Goiatuba - GO",
  "Centro Universitário de Mineiros - UNIFIMES (GO)",
  "Centro Universitário de Mineiros - UNIFIMES-Trindade -GO",
  "Faculdade Alfredo Nasser - Aparecida de Goiania - GO - UNIFAN",
  "Pontifícia Universidade Católica de Goiás - PUC-GO",
  "Universidade de Rio Verde - Aparecida de Goiania - GO UniRV",
  "Universidade de Rio Verde - UniRV - Rio Verde/GO",
  "Universidade de Rio Verde - UniRV/GO - Goianésia",
  "Universidade de Rio Verde -Formosa- Unirv -",
  "Universidade Estadual de Goiás/campus Itumbiara",
  "Universidade Federal de Goias - Campus de Catalão - UFG-UC",
  "Universidade Federal de Goiás - Jataí/Go",
  "Universidade Federal de Goiás - UFG",
  "Centro Universitário Unidade de Ensino Superior Dom Bosco",
  "Faculdade de Ciências e Saúde Edufor - EDUFOR",
  "Faculdade Pitágoras - Codó - Maranhão",
  "Universidade Ceuma - Imperatriz/MA - UNICEUMA./IMPERATRIZ",
  "Universidade do Ceuma-UNICEUMA",
  "Universidade Estadual do Maranhão- Caxias - UEMA",
  "Universidade Federal do Maranhão - São Luis - UFMA",
  "Universidade Federal do Maranhão - UFMA-Pinheiro (MA)",
  "Universidade Federal do Maranhão- UFMA-Imperatriz (MA)",
  "AFYA Faculdade de Ciências Médicas de Contagem",
  "Afya Faculdade de Ciências Médicas de Ipatinga",
  "Centro Universitário Atenas - Paracatu-MG - UNIATENAS",
  "Centro Universitário de Belo Horizonte/MG - UNI-BH",
  "Centro Universitário de Caratinga - UNEC",
  "Centro Universitário de Itajubá - FEPI",
  "Centro Universitário de Patos de Minas - UNIPAM",
  "Centro Universitário do Planalto de Araxá - UNIARAXÁ",
  "Centro Universitário do Triângulo - Uberlândia/MG - UNITRI",
  "Centro Universitário Estácio de Belo Horizonte",
  "Centro Universitário Faminas - Belo Horizonte",
  "Centro Universitário Faminas - Muriaé",
  "Centro Universitário Newton Paiva - Belo Horizonte",
  "Centro Universitário UNIFACIG",
  "Centro Universitário UNIFAMINAS",
  "Centro Universitário UNIPTAN",
  "Centro Universitário UNA - Belo Horizonte/MG",
  "Escola Superior de Ciências da Saúde - Belo Horizonte/MG",
  "Faculdade de Ciências Médicas de Minas Gerais - Belo Horizonte - FCMMG",
  "Faculdade de Medicina de Barbacena - FAME",
  "Faculdade de Medicina de Itajubá - FMIT",
  "Faculdade de Medicina de Minas Gerais - Belo Horizonte",
  "Faculdade de Medicina de Pouso Alegre - UNIVÁS",
  "Faculdade de Medicina de São João del-Rei - UFSJ",
  "Faculdade de Medicina de Uberaba - UNIUBE",
  "Faculdade de Medicina do Vale do Aço - Ipatinga/MG - UNIVAÇO",
  "Faculdade Dinâmica do Vale do Piranga",
  "Faculdade Santa Rita - Conselheiro Lafaiete/MG",
  "Fundação Educacional de Patos de Minas - FEPAM",
  "Instituto de Ensino Superior de Minas Gerais - IESMG",
  "Pontifícia Universidade Católica de Minas Gerais - PUC-MG",
  "Universidade do Estado de Minas Gerais - UEMG",
  "Universidade Federal de Alfenas - UNIFAL",
  "Universidade Federal de Juiz de Fora - UFJF",
  "Universidade Federal de Minas Gerais - UFMG",
  "Universidade Federal de Ouro Preto - UFOP",
  "Universidade Federal de São João del-Rei - UFSJ",
  "Universidade Federal de Uberlândia - UFU",
  "Universidade Federal de Viçosa - UFV",
  "Universidade Federal do Triângulo Mineiro - UFTM",
  "Universidade Federal dos Vales do Jequitinhonha e Mucuri - UFVJM",
  "Universidade Vale do Rio Verde - UNINCOR",
  "Universidade Vale do Rio Doce - UNIVALE",
  "Centro Universitário de Campo Grande - UNIDERP",
  "Centro Universitário de Grande Dourados - UNIGRAN",
  "Universidade Estadual de Mato Grosso do Sul - UEMS",
  "Universidade Federal da Grande Dourados - UFGD",
  "Universidade Federal de Mato Grosso do Sul - UFMS",
  "Centro Universitário de Cuiabá - UNIC",
  "Centro Universitário de Várzea Grande - UNIVAG",
  "Faculdade de Medicina de Tangará da Serra - UNIC",
  "Universidade Federal de Mato Grosso - UFMT",
  "Universidade do Estado de Mato Grosso - UNEMAT",
  "Centro Universitário do Pará - CESUPA",
  "Centro Universitário Planalto Central - UNICEPLAC",
  "Faculdade de Medicina de Marabá - FACIMPA",
  "Universidade do Estado do Pará - UEPA",
  "Universidade Federal do Pará - UFPA",
  "Universidade Federal do Oeste do Pará - UFOPA",
  "Faculdade de Medicina de Araruna - UEPB",
  "Faculdade de Medicina de Campina Grande - UFCG",
  "Faculdade de Medicina de João Pessoa - UFPB",
  "Universidade Estadual da Paraíba - UEPB",
  "Universidade Federal da Paraíba - UFPB",
  "Universidade Federal de Campina Grande - UFCG",
  "Centro Universitário de João Pessoa - UNIPÊ",
  "Faculdade de Medicina de Olinda - FMO",
  "Faculdade Pernambucana de Saúde - FPS",
  "Universidade de Pernambuco - UPE",
  "Universidade Federal de Pernambuco - UFPE",
  "Universidade Federal do Vale do São Francisco - UNIVASF",
  "Centro Universitário Christus - UNICHRISTUS",
  "Centro Universitário de Teresina - UNIFACID",
  "Universidade Estadual do Piauí - UESPI",
  "Universidade Federal do Piauí - UFPI",
  "Faculdade de Medicina de Cascavel - FAG",
  "Faculdade de Medicina de Maringá - UNICESUMAR",
  "Pontifícia Universidade Católica do Paraná - PUC-PR",
  "Universidade Estadual de Londrina - UEL",
  "Universidade Estadual de Maringá - UEM",
  "Universidade Estadual de Ponta Grossa - UEPG",
  "Universidade Estadual do Oeste do Paraná - UNIOESTE",
  "Universidade Federal do Paraná - UFPR",
  "Centro Universitário de Curitiba - UNICURITIBA",
  "Universidade Positivo - UP",
  "Centro Universitário Serra dos Órgãos - UNIFESO",
  "Faculdade de Medicina de Petrópolis - FMP",
  "Fundação Técnico-Educacional Souza Marques - FTESM",
  "Pontifícia Universidade Católica do Rio de Janeiro - PUC-Rio",
  "Universidade do Estado do Rio de Janeiro - UERJ",
  "Universidade Federal do Estado do Rio de Janeiro - UNIRIO",
  "Universidade Federal do Rio de Janeiro - UFRJ",
  "Universidade Federal Fluminense - UFF",
  "Universidade Iguaçu - UNIG",
  "Universidade Estácio de Sá - UNESA",
  "Faculdade de Medicina de Mossoró - UERN",
  "Universidade Estadual do Rio Grande do Norte - UERN",
  "Universidade Federal do Rio Grande do Norte - UFRN",
  "Faculdade de Medicina de Porto Velho - UNIRON",
  "Universidade Federal de Rondônia - UNIR",
  "Universidade Federal de Roraima - UFRR",
  "Faculdade de Medicina de Passo Fundo - UPF",
  "Faculdade de Medicina de Pelotas - UFPEL",
  "Pontifícia Universidade Católica do Rio Grande do Sul - PUC-RS",
  "Universidade Federal de Ciências da Saúde de Porto Alegre - UFCSPA",
  "Universidade Federal de Pelotas - UFPEL",
  "Universidade Federal de Santa Maria - UFSM",
  "Universidade Federal do Rio Grande - FURG",
  "Universidade Federal do Rio Grande do Sul - UFRGS",
  "Universidade de Caxias do Sul - UCS",
  "Universidade Luterana do Brasil - ULBRA",
  "Universidade do Vale do Itajaí - UNIVALI",
  "Universidade Federal de Santa Catarina - UFSC",
  "Universidade do Sul de Santa Catarina - UNISUL",
  "Universidade Regional de Blumenau - FURB",
  "Universidade Federal de Sergipe - UFS",
  "Universidade Tiradentes - UNIT",
  "Centro Universitário das Faculdades Associadas de Ensino - UNIFAE",
  "Centro Universitário de Araraquara - UNIARA",
  "Centro Universitário de Marília - UNIMAR",
  "Centro Universitário de Rio Preto - UNIRP",
  "Centro Universitário de Votuporanca - UNIFEV",
  "Centro Universitário do Estado de São Paulo - UNIESP",
  "Centro Universitário Lusíada - UNILUS",
  "Centro Universitário Padre Albino - UNIFIPA",
  "Centro Universitário São Camilo",
  "Escola de Medicina da Santa Casa de Misericórdia de São Paulo - FCMSCSP",
  "Escola Paulista de Medicina - UNIFESP",
  "Faculdade de Medicina de Botucatu - UNESP",
  "Faculdade de Medicina de Catanduva - FAMECA",
  "Faculdade de Medicina de Jundiaí - FMJ",
  "Faculdade de Medicina de Marília - FAMEMA",
  "Faculdade de Medicina de Ribeirão Preto - USP",
  "Faculdade de Medicina de São José do Rio Preto - FAMERP",
  "Faculdade de Medicina de Sorocaba - PUC-SP",
  "Faculdade de Medicina do ABC - FMABC",
  "Faculdade de Medicina da USP - FMUSP",
  "Pontifícia Universidade Católica de Campinas - PUC-Campinas",
  "Universidade Cidade de São Paulo - UNICID",
  "Universidade de Franca - UNIFRAN",
  "Universidade de Mogi das Cruzes - UMC",
  "Universidade de Ribeirão Preto - UNAERP",
  "Universidade de Santo Amaro - UNISA",
  "Universidade de São Paulo - USP",
  "Universidade de Taubaté - UNITAU",
  "Universidade do Oeste Paulista - UNOESTE",
  "Universidade Estadual de Campinas - UNICAMP",
  "Universidade Federal de São Carlos - UFSCar",
  "Universidade Federal de São Paulo - UNIFESP",
  "Universidade Nove de Julho - UNINOVE",
  "Universidade Santa Cecília - UNISANTA",
  "Universidade São Francisco - USF",
  "Universidade Federal do Tocantins - UFT",
  "Centro Universitário ITPAC",
  "Faculdade de Medicina de Gurupi - UNIRG"
];
